security:
    encoders:
        App\Entity\User:
            algorithm: auto

    providers:
        user_provider:
            id: App\Security\Provider\UserProvider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        user:
            anonymous: ~
            form_login:
                login_path: api_login
                use_referer: true

            logout:
                path: app_logout
                target: home

            provider: user_provider

            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator


    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
    # - { path: ^/admin, roles: ROLE_ADMIN }
    # - { path: ^/profile, roles: ROLE_USER }
